### ISSUE TITLE
Upgrade phpdocumentor/reflection-docblock to 3.x

### ISSUE THREAD

**Issue by spideyfusion** [consolidation-org/annotated-command#32]
It seems that [phpspec/prophecy](https://github.com/phpspec/prophecy/) has resolved their dependency issues:

https://github.com/phpspec/prophecy/pull/275

Can AnnotatedCommand now be updated so it targets the 3.x branch of [phpdocumentor/reflection-docblock](https://github.com/phpdocumentor/reflection-docblock/)?

This would resolve compatibility issues with Symfony 3.1.

**Comment by spideyfusion** [comment]
@greg-1-anderson Got any feedback regarding this?

**Comment by greg-1-anderson** [comment]
I'll create a version 2.x for this.  The master branch will be 2.x, and I will create a 1.x branch to continue the old line, for folks still on the older phpunit.

At this time, I do not plan large changes to either branch.

**Comment by greg-1-anderson** [comment]
Fixed in d0144c2, tagged as 1.2.0.  Since phpspec/prophecy supports both the 2.x and 3.x branches of  phpdocumentor/reflection-docblock, I was able to do the same thing here, obviating the need for a 2.x branch of consolidation/annotated-command.
